### ISSUE TITLE
ReferenceError: e is not defined

### ISSUE THREAD

**Issue by alanwangfan** [gamesys/moonshine#23]
I'm afraid there is a bug  in distil.js. I can't know what's the real reason that  use moonshine to distil my lua file unsuccessfully like this: 

D:\lua>moonshine distil hello.lua

C:\Users\w00222107\AppData\Roaming\npm\node_modules\moonshine\bin\commands\distil.js:154
                        if (errPart[1] != 'luac') throw e;
                                                        ^
ReferenceError: e is not defined
    at C:\Users\w00222107\AppData\Roaming\npm\node_modules\moonshine\bin\commands\distil.js:154:36
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

**Comment by goto-bus-stop** [comment]
#13 :smile:

**Comment by paulcuth** [comment]
Fixed in https://github.com/gamesys/moonshine/commit/0ef4f829036fb444f31fdaea7a2efba840004490.
